/**
 * What the assistant may talk about beyond SnapWell's own data.
 *
 * With general knowledge allowed, the assistant also answers everyday food and
 * cooking questions from the model's own knowledge. Those answers are not
 * verified the way tool-backed ones are, so the chat labels them. Medical and
 * health advice stays out either way, and is enforced twice: the prompt tells
 * the model not to give it, and the check below catches it in the question
 * before any request is made and in the reply before it is shown.
 *
 * Switch this off to return to the strict assistant that answers only from the
 * app's own data.
 */
export const ALLOW_GENERAL_FOOD_KNOWLEDGE = true

export const AI_GENERATED_NOTE = 'Generated by AI · please double-check'

export const APP_ANSWER_NOTE = 'Answered by SnapWell, not the AI'

/**
 * Kind, brief, and back to the kitchen. It is worded to avoid the health terms
 * below, so the app's own refusal can never trip the check it answers for.
 */
export const HEALTH_REFUSAL = 'That one is best answered by a doctor or an Accredited Practising '
  + 'Dietitian, so I\'ll leave it to them. I\'d love to help with the cooking side, though — ask me '
  + 'how to make one of your recipes, or what you could cook with your ingredients.'

/**
 * Terms that mark a health question. Each is written narrowly enough to leave
 * food alone: kidney beans, chicken liver and 山药 (yam) are ingredients, and
 * the app's own "Weight loss" goal is a preference, not a request for advice.
 * A few false positives are an accepted cost; letting health advice through is
 * not.
 */
const HEALTH_TERMS = [
  /\bdiabet(?:es|ic)\b/i,
  /\bblood (?:sugar|glucose|pressure)\b/i,
  /\binsulin\b/i,
  /\bhypertension\b/i,
  /\bcholesterol\b/i,
  /\bheart (?:disease|attack|condition|failure)\b/i,
  /\bkidney (?:disease|stones?|failure|function)\b/i,
  /\bliver (?:disease|damage|function)\b/i,
  /\bcancer\b/i,
  /\bpregnan(?:t|cy)\b/i,
  /\bbreast ?feeding\b/i,
  /\bmedications?\b/i,
  /\bmedicines?\b/i,
  /\bprescri(?:bed|ptions?)\b/i,
  /\bsupplements?\b/i,
  /\bsymptoms?\b/i,
  /\banaphyla(?:xis|ctic)\b/i,
  /\ballergic reactions?\b/i,
  /\bco?eliac disease\b/i,
  /\bgout\b/i,
  /\bthyroid\b/i,
  /\bpcos\b/i,
  /\bcrohn'?s\b/i,
  /\beating disorders?\b/i,
  /\blos(?:e|ing) weight\b/i,
  /\bcalorie deficit\b/i,
  /\bdiet plans?\b/i,
  /糖尿病|血糖|胰岛素|血压|胆固醇|心脏病|肾病|肾结石|肝病|脂肪肝|癌症|怀孕|孕妇|孕期|哺乳|药物|吃药|服药|处方|保健品|补充剂|症状|过敏反应|痛风|甲状腺|减肥|减重|瘦身|饮食计划/,
]

/** The first health term in the text, or null when there is none. */
export function detectHealthTopic(text) {
  const value = String(text ?? '')
  for (const pattern of HEALTH_TERMS) {
    const match = value.match(pattern)
    if (match) return match[0]
  }
  return null
}

/**
 * Whether an answer carries the AI-generated label. The model's own flag
 * counts, and so does an answer that used no tool at all, because that flag is
 * self-reported. A polite decline is the exception: it states nothing worth
 * double-checking. The app's own answers are never labelled.
 */
export function shouldShowAiNote({
  generalKnowledge = false,
  declined = false,
  answeredByApp = false,
  toolCallCount = 0,
  allowGeneral = ALLOW_GENERAL_FOOD_KNOWLEDGE,
} = {}) {
  if (!allowGeneral || answeredByApp) return false
  if (generalKnowledge) return true
  return toolCallCount === 0 && !declined
}
